### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by pnorman** [mojodna/tapalcatl-2-spec#2]
The spec does not have a license, preventing others from expanding on it, and posing barriers to contributing.

The text the [tilejson spec uses](https://github.com/mapbox/tilejson-spec) is The text of this specification is licensed under a [Creative Commons Attribution 3.0 United States License](https://creativecommons.org/licenses/by/3.0/us/). However, the use of this spec in products and code is entirely free: there are no royalties, restrictions, or requirements.

**Comment by sethfitz** [comment]
I’ll fix this when I’m not on mobile. It’ll either be CC-BY or CC-0.
